// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiymplhjhxgoyuubqevu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpeW1wbGhqaHhnb3l1dWJxZXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTcwODEsImV4cCI6MjA2NDMzMzA4MX0.mKVmSNmg4Va7j5pl5sKn1joctmN-gepi1J1rJDosg1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);