- name: Push changes
  run: |
    git config --global user.name "FB Sync Bot"
    git config --global user.email "fbsync@bot.com"
    git add data.json
    git commit -m "Update FB data"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.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 }}  # Token automático de GitHub
